import { NextRequest, NextResponse } from 'next/server';
import { z } from 'zod';

import { authenticateSkillRequest } from '@/lib/assessment-skill/request-auth';
import { recordAiConversationEvent } from '@/lib/services/ai-conversation-log';
import { synthesizeSpeechWithProvider } from '@/lib/services/ttsProvider';

const requestSchema = z.object({
  text: z.string().min(1),
  conversationSessionId: z.string().optional(),
  memberProfileId: z.string().optional(),
  assessmentSessionId: z.string().optional(),
  assessmentHistoryId: z.string().optional(),
  doctorProfileId: z.string().optional(),
  scaleId: z.string().optional(),
  questionId: z.number().optional(),
  voiceId: z.string().optional(),
  speed: z.number().min(0.5).max(2).optional(),
  pitch: z.number().min(0.5).max(2).optional(),
  format: z.enum(['mp3', 'wav', 'ogg']).optional(),
});

export async function POST(request: NextRequest) {
  try {
    const session = authenticateSkillRequest(request, 'skill:voice-intent');
    const body = requestSchema.parse(await request.json());

    const result = await synthesizeSpeechWithProvider({
      text: body.text,
      voiceId: body.voiceId,
      speed: body.speed,
      pitch: body.pitch,
      format: body.format,
    });

    const logged = await recordAiConversationEvent({
      conversationSessionId: body.conversationSessionId,
      userId: session.sub,
      memberProfileId: body.memberProfileId,
      assessmentSessionId: body.assessmentSessionId,
      assessmentHistoryId: body.assessmentHistoryId,
      doctorProfileId: body.doctorProfileId,
      scaleId: body.scaleId,
      questionId: body.questionId,
      eventType: 'tts_output',
      provider: result.provider,
      model: result.model,
      assistantText: body.text,
      summary: 'API TTS output generated by project-side adapter',
      metadata: {
        mimeType: result.mimeType,
        format: body.format || 'mp3',
        voiceId: body.voiceId,
      },
    });

    return NextResponse.json({
      success: true,
      conversationSessionId: logged.session.id,
      provider: result.provider,
      model: result.model,
      mimeType: result.mimeType,
      audioBase64: result.audioBase64,
    });
  } catch (error) {
    if (error instanceof z.ZodError) {
      return NextResponse.json({ error: error.flatten() }, { status: 400 });
    }

    return NextResponse.json(
      { error: error instanceof Error ? error.message : 'TTS synthesis failed' },
      { status: 500 }
    );
  }
}
